version: '2'
services:
  php-apache:
    build: .
    ports:
      - "80:80"
      - "443:433"
    volumes:
      - /home/bernard/Dev/external:/var/www
      - /home/bernard/Backup/Docker/Volumes/logs:/var/log
    links:
      - mysql
    networks:
      - default

  mysql:
    image: mysql
    ports:
      - "33061:3306"
      - "3306:3306"
    volumes:
      - /home/bernard/Backup/Docker/Volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
